import TransitionEffect from '@/components/TransitionEffect';
import Layout from '@/components/Layout';
import Head from 'next/head';
import React from 'react';
import AnimatedText from '@/components/AnimatedText';

const contact = () => {

	const handleSubmit = () => {
		
	}

	return (
		<>

			<Head>
				<title>Chinmay Dandekar | Home Page</title>
				<meta name="description" content="Generated by create next app" />

			</Head>
			<TransitionEffect />
			<main className='flex w-full flex-col items-center justify-center dark:text-light'>
				<Layout className="pt-4">
					<AnimatedText text={"Get In Touch."} />
					<div className='grid grid-cols-8 w-full  h-auto py-10'>
						<form
							onSubmit={handleSubmit}
							className='col-span-4 w-[70%]  h-max mx-auto p-16 flex flex-col items-start justify-center relative rounded-2xl border-2 border-solid border-dark bg-light dark:bg-dark dark:border-light'>
							<div className='absolute top-0 -right-3 -z-10 w-[102%] h-[102%] rounded-[2rem] bg-dark dark:bg-light  ' />
							<div className='mb-12  w-full h-auto'>
								<label className='font-bold text-xl text-dark dark:text-light mb-2'>Name</label>
								<input type="text" className=' w-full h-10 border-0 border-solid border-b-primary border-b-4 bg-light outline-none text-dark/75 text-xl font-medium dark:text-light/75 dark:border-b-primaryDark dark:bg-dark' />
							</div>
							<div className='  w-full h-auto'>
								<label className='font-bold text-xl text-dark dark:text-light mb-2'>Email</label>
								<input type="email" className=' w-full h-10 border-0 border-solid border-b-primary border-b-4 bg-light outline-none text-dark/75 text-xl font-medium dark:text-light/75 dark:border-b-primaryDark dark:bg-dark' />
							</div>
							<div className='mt-12  w-full h-auto'>
								<label className='font-bold text-xl text-dark dark:text-light mb-2'>Message</label>
								<textarea type="email" className=' w-full h-10 border-0 border-solid border-b-primary border-b-4 bg-light outline-none text-dark/75 text-xl font-medium dark:text-light/75 dark:border-b-primaryDark dark:bg-dark' />
							</div>
						</form>
						<div className='col-span-4'>

						</div>
					</div>
				</Layout>
			</main>

		</>
	)
}

export default contact